language: ruby
sudo: false
cache: bundler
bundler_args: --without tools
script: "bundle exec rake ci"
rvm:
  - 2.0
  - 2.1
  - 2.2
  - rbx-2
  - jruby-9000
  - jruby-head
  - ruby-head
env:
  global:
    - CODECLIMATE_REPO_TOKEN=15dad2a6b4f5f73f367783df8192230b73070b33fe1f193393e9867d50653885
    - JRUBY_OPTS='--dev -J-Xmx1024M'
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/39e1225f489f38b0bd09
    on_success: change
    on_failure: always
    on_start: false
